import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Img1Webp from '../../public/images/mv_text_1.webp'
import Img1Png from '../../public/images/mv_text_1.png'
import Img2Webp from '../../public/images/mv_text_2.webp'
import Img2Png from '../../public/images/mv_text_2.png'
import Img3Webp from '../../public/images/mv_img_1.webp'
import Img3Png from '../../public/images/mv_img_1.png'
import Img4Webp from '../../public/images/mv_text_3.webp'
import Img4Png from '../../public/images/mv_text_3.png'
import Link from 'next/link'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="block">
        <div className="relative h-[100vh] w-[100%]">
          <div className="rounded-[4px] box-border h-[592px] max-w-[432px] 
          py-0 px-[1rem] w-[100%] absolute top-[50%] left-[50%] translate-y-[-50%] translate-x-[-50%]">
            <p className="mt-0 mx-auto mb-5 w-4/5 mt-[20px]">
              <picture className="">
                <source srcSet={Img1Webp.src} />
                <img src={Img1Png.src} alt="満足度93% 次世代キャリアスクール開発の最新版" loading="lazy"
                  className="w-full" width="320" height="200" />
              </picture>
            </p>
            <h1 className="my-0 mx-auto w-2/3">
              <picture className="">
                <source srcSet={Img2Webp.src} />
                <img src={Img2Png.src} alt="強み・弱みx適正職業がたった1分の回答で今すぐわかる適職診断byキャリドラ"
                  className="w-full" loading="lazy" width="320" height="200" />
              </picture>
            </h1>
            <figure className="p-mv__image">
              <picture className="">
                <source srcSet={Img3Webp.src} />
                <img src={Img3Png.src} alt="様々な職種の人々の画像" loading="lazy"
                  className="w-full" width="320" height="200" />
              </picture>
            </figure>
            <p className="p-mv__point">
              <picture className="">
                <source srcSet={Img4Webp.src} />
                <img src={Img4Png.src} alt="こんなあなたにぴったり！自分の強みを活かせる職業を知りたい/今よりキャリアアップするヒントが欲しい/今の環境を変えて年収も上げたい" loading="lazy"
                  className="w-full" width="320" height="200" />
              </picture>
            </p>
            <Link href="/questionsContainer">
              <button className="fixed text-center mt-[20px] ml-[140px]">
                <a className="block shadow-lg px-2 py-1  bg-blue-400 text-lg text-white font-semibold rounded  hover:bg-blue-500 hover:shadow-sm hover:translate-y-0.5 transform transition ">結果画面へ!!</a>
              </button>
            </Link>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
