import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Img1Webp from '../../public/images/mv_text_1.webp'
import Img1Png from '../../public/images/mv_text_1.png'
import Img2Webp from '../../public/images/mv_text_2.webp'
import Img2Png from '../../public/images/mv_text_2.png'
import Img3Webp from '../../public/images/mv_img_1.webp'
import Img3Png from '../../public/images/mv_img_1.png'
import Img4Webp from '../../public/images/mv_text_3.webp'
import Img4Png from '../../public/images/mv_text_3.png'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="block">
        <div className="padding: 25px 0 40px;">
          <div className="p-mv__inner">
            <p className="p-mv__lead">
              <picture className="">
                <source srcSet={Img1Webp.src} />
                <img src={Img1Png.src} alt="満足度93% 次世代キャリアスクール開発の最新版" loading="lazy"
                  width="320" height="200" />
              </picture>
            </p>
            <h1 className="p-mv__heading">
                <picture className="">
                  <source srcSet={Img2Webp.src} />
                  <img src={Img2Png.src} alt="強み・弱みx適正職業がたった1分の回答で今すぐわかる適職診断byキャリドラ"
                    loading="lazy" width="320" height="200" />
                </picture>
              </h1>
              <figure className="p-mv__image">
                <picture className="">
                    <source srcSet={Img3Webp.src} />
                    <img src={Img3Png.src} alt="様々な職種の人々の画像" loading="lazy" width="320"
                        height="200"/>
                </picture>
            </figure>
            <p className="p-mv__point">
                <picture className="">
                    <source srcSet={Img4Webp.src} />
                    <img src={Img4Png.src} alt="こんなあなたにぴったり！自分の強みを活かせる職業を知りたい/今よりキャリアアップするヒントが欲しい/今の環境を変えて年収も上げたい" loading="lazy"
                        width="320" height="200" />
                </picture>
            </p>
          </div>
        </div>
      </main>
      {/* <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">
          Hello Yamano Next.js!
        </h1>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main> */}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
